### ISSUE TITLE
Unreasonably slow unification during type class resolution

### ISSUE THREAD

**Issue by YaZko** [damien-pous/coinduction#2]
Hello,

Typically during type class resolution, huge unification problems can be seemingly randomly triggered by dead branches. 

The minimal example below illustrates the issue: although a trivial resolution of `Reflexive eq` exists, the presence of the `isot_equiv` instance in the context leads the solver to first explore thousands of incorrect unification branches by seemingly testing myriads of lattices as arguments to `t`.

On this minimal example, resolution remains instantaneous, but running the debug tool can already showcase the explosion. In more involved contexts, it has led to a 30s wait.

As discussed with @damien-pous, preventing typeclass resolution to peek into the definition of `t` solves the problem. A lightweight solution is therefore to use the `Typeclasses Opaque t` command.

It should be noted that there may be non-typeclass-resolution contexts in which these unification problems could arise, in which case this fix would be insufficient, but I haven't observed any so far.

Best,
Yannick

```
From Coinduction Require Import 
	coinduction rel tactics.

Section Unification.

	Variable X : Type.
	Variable feq  : mon (X -> X -> Prop).
	Variable fiso : mon (X -> X -> Prop).

	Notation eq  := (gfp feq).
	Notation iso := (gfp fiso).

	(* Let us consider an Equivalence instance for eq *)
	Instance eq_equiv : Equivalence eq.
	Admitted.

	(* Résolvons Reflexive *)
	Goal Reflexive eq.
	  typeclasses eauto. (* Instantané *)
		Restart.
  	Set Debug Tactic Unification. (* Pour afficher les unification ayant lieu *)
  	typeclasses eauto. (* 78 lignes d'output *)
	Qed.

	Unset Debug Tactic Unification.

	(* Supposons maintenant qu'on a aussi dans notre contexte une Equivalence pour (t fiso) *)
	Instance isot_equiv R : Equivalence (t fiso R).
	Admitted.

	Goal Reflexive eq.
  	typeclasses eauto. (* Encore instantané sur un exemple aussi simple, mais 30s dans mon cas *)
		Restart.
		Set Debug Tactic Unification.
  	typeclasses eauto. (* Mais déjà 27 352 lignes d'output *)
	Admitted.

End Unification.

```

**Comment by damien-pous** [comment]
Thanks @YaZko, fixed with [Typeclass Opaque t B T] (commit 22340336ab0121435fa4c76b9cdf2e1fefb03287).
Will reopen if the problem appears again with other instances of unification.

**Comment by YaZko** [comment]
Unfortunately, the issue is back. I am not sure why (I suppose it is fairly random), but the unification gets lost into lattice-land in other contexts where it happened to go smoothly before. Below is a minimal example, that indeed does not rely on type classes, but simply the application of a lemma from the library (`Equivalence_T`). Naturally adding arguments that specify explicitly the lattice solves the issue, but hopefully there's a way to prevent it altogether to loop as it does here.

```
From Coinduction Require Import 
	coinduction rel tactics.

Section Unification.

	Variable X : Type.
	Variable fbisim  : mon (X -> X -> Prop).

	Notation bisim := (gfp fbisim).

	Lemma refl_t : const eq <= t fbisim.
	Admitted.

	#[global] Instance Equivalence_T f S: Equivalence (t (B fbisim) f S).
	Proof.
		Fail Timeout 2 apply Equivalence_T. (* Does not seem to converge *)
		apply (Equivalence_T refl_t).
	Abort.

End Unification.
```

**Comment by YaZko** [comment]
Oh I see I've been using an unfolding of `T` instead of the definition for some reason, using it explicitly (i.e. `Equivalence (T fbisim f S)`) does avoid the problem.
